const PerformersData = [
  {
    key: "performerData1",
    profileImg: "/images/profile/user-3.jpg",
    username: "Sunil Joshi",
    designation: "طراح وب",
    project: "Elite Admin",
    priority: "کم",
    bgcolor: "bg-primary text-white",
    budget: "3.9k",
  },
  {
    key: "performerData2",
    profileImg: "/images/profile/user-5.jpg",
    username: "John Deo",
    designation: "توسعه‌دهنده وب",
    project: "Flexy Admin",
    priority: "متوسط",
    color: "warning",
    bgcolor: "bg-warning text-white",
    budget: "24.5k",
  },
  {
    key: "performerData3",
    profileImg: "/images/profile/user-6.jpg",
    username: "Nirav Joshi",
    designation: "مدیر وب",
    project: "Material Pro",
    priority: "زیاد",
    color: "warning",
    budget: "12.8k",
  },
  {
    key: "performerData4",
    profileImg: "/images/profile/user-7.jpg",
    username: "Yuvraj Sheth",
    designation: "مدیر پروژه",
    project: "Xtreme Admin",
    priority: "کم",
    color: "success",
    bgcolor: "bg-success text-white",
    budget: "4.8k",
  },
  {
    key: "performerData5",
    profileImg: "/images/profile/user-8.jpg",
    username: "Micheal Doe",
    designation: "نویسنده محتوا",
    project: "Helping Hands WP Theme",
    priority: "زیاد",
    color: "error",
    bgcolor: "bg-error text-white",
    budget: "9.3k",
  },
];
export { PerformersData };
