import type {
  DomainConfig,
  RealEstateRow,
  HealthcareRow,
  InsuranceRow,
  MarketingRow,
  MarketplaceRow,
} from "./types";

// ─── Real Estate ────────────────────────────────────────────────────────────
export const realEstateConfig: DomainConfig<RealEstateRow> = {
  type: "realEstate",
  label: "املاک",
  icon: "solar:buildings-2-linear",
  stats: [
    {
      id: "re1",
      label: "کل ملک‌ها",
      value: "۱٬۲۴۸",
      change: "+۱۲٪",
      changeType: "up",
      icon: "solar:buildings-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "re2",
      label: "آگهی فعال",
      value: "۳۸۶",
      change: "+۸٪",
      changeType: "up",
      icon: "solar:tag-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "re3",
      label: "فروش ماهانه",
      value: "۴۵ میلیارد",
      change: "-۳٪",
      changeType: "down",
      icon: "solar:hand-money-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "re4",
      label: "میانگین قیمت",
      value: "۸.۵ میلیارد",
      change: "+۵٪",
      changeType: "up",
      icon: "solar:graph-up-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
  charts: {
    primary: {
      title: "روند فروش ملک (ماهانه)",
      type: "line",
      categories: [
        "فروردین",
        "اردیبهشت",
        "خرداد",
        "تیر",
        "مرداد",
        "شهریور",
        "مهر",
        "آبان",
        "آذر",
        "دی",
        "بهمن",
        "اسفند",
      ],
      series: [
        {
          name: "فروش",
          data: [32, 45, 38, 52, 61, 55, 48, 70, 65, 58, 74, 80],
        },
        {
          name: "اجاره",
          data: [18, 22, 25, 30, 28, 35, 32, 40, 38, 45, 42, 50],
        },
      ],
    },
    secondary: {
      title: "آگهی‌ها بر اساس شهر",
      type: "bar",
      categories: ["تهران", "اصفهان", "مشهد", "شیراز", "تبریز", "کرج"],
      series: [
        { name: "آپارتمان", data: [120, 68, 54, 45, 38, 30] },
        { name: "ویلا", data: [45, 28, 22, 18, 15, 12] },
        { name: "تجاری", data: [30, 18, 14, 10, 8, 6] },
      ],
    },
  },
  tableData: [
    {
      id: "re-t1",
      title: "آپارتمان ۱۲۰ متری نیاوران",
      location: "تهران، نیاوران",
      price: "۱۲.۵ میلیارد",
      type: "آپارتمان",
      status: "فروش",
      agent: "رضا احمدی",
    },
    {
      id: "re-t2",
      title: "ویلای ۳۰۰ متری لواسان",
      location: "تهران، لواسان",
      price: "۴۸ میلیارد",
      type: "ویلا",
      status: "فروش",
      agent: "سارا محمدی",
    },
    {
      id: "re-t3",
      title: "دفتر تجاری ۸۵ متری ولیعصر",
      location: "تهران، ولیعصر",
      price: "۱۸ میلیارد",
      type: "تجاری",
      status: "اجاره",
      agent: "علی کریمی",
    },
    {
      id: "re-t4",
      title: "آپارتمان ۹۰ متری اصفهان",
      location: "اصفهان، چهارباغ",
      price: "۶.۸ میلیارد",
      type: "آپارتمان",
      status: "فروخته شد",
      agent: "مریم حسینی",
    },
    {
      id: "re-t5",
      title: "زمین ۵۰۰ متری کرج",
      location: "کرج، گوهردشت",
      price: "۹ میلیارد",
      type: "زمین",
      status: "فروش",
      agent: "حمید نظری",
    },
    {
      id: "re-t6",
      title: "مغازه ۴۵ متری مشهد",
      location: "مشهد، احمدآباد",
      price: "۴.۲ میلیارد",
      type: "تجاری",
      status: "اجاره",
      agent: "فاطمه رضوی",
    },
  ],
  activityFeed: [
    {
      id: "a1",
      title: "آگهی جدید ثبت شد",
      subtitle: "آپارتمان ۱۵۰ متری - تهران",
      time: "۱۰ دقیقه پیش",
      icon: "solar:add-circle-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "a2",
      title: "قرارداد منعقد شد",
      subtitle: "ویلای لواسان - ۴۸ میلیارد",
      time: "۱ ساعت پیش",
      icon: "solar:document-add-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "a3",
      title: "بازدید تایید شد",
      subtitle: "مشتری: محمد رضایی",
      time: "۲ ساعت پیش",
      icon: "solar:eye-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "a4",
      title: "قیمت به‌روز شد",
      subtitle: "دفتر ولیعصر - کاهش ۵٪",
      time: "۵ ساعت پیش",
      icon: "solar:pen-linear",
      iconBg: "bg-info/10",
      iconColor: "text-info",
    },
    {
      id: "a5",
      title: "آگهی منقضی شد",
      subtitle: "مغازه احمدآباد",
      time: "دیروز",
      icon: "solar:bell-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
};

// ─── Healthcare ─────────────────────────────────────────────────────────────
export const healthcareConfig: DomainConfig<HealthcareRow> = {
  type: "healthcare",
  label: "سلامت",
  icon: "solar:heart-pulse-2-linear",
  stats: [
    {
      id: "hc1",
      label: "کل بیماران",
      value: "۸٬۵۳۲",
      change: "+۱۵٪",
      changeType: "up",
      icon: "solar:users-group-rounded-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "hc2",
      label: "ویزیت امروز",
      value: "۱۴۲",
      change: "+۶٪",
      changeType: "up",
      icon: "solar:calendar-date-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "hc3",
      label: "درآمد ماهانه",
      value: "۳.۲ میلیارد",
      change: "+۱۸٪",
      changeType: "up",
      icon: "solar:wallet-money-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "hc4",
      label: "اشغال تخت",
      value: "۷۸٪",
      change: "-۴٪",
      changeType: "down",
      icon: "solar:bed-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
  charts: {
    primary: {
      title: "مراجعات بیمار (هفتگی)",
      type: "area",
      categories: [
        "شنبه",
        "یکشنبه",
        "دوشنبه",
        "سه‌شنبه",
        "چهارشنبه",
        "پنجشنبه",
        "جمعه",
      ],
      series: [
        { name: "سرپایی", data: [85, 120, 115, 98, 130, 110, 45] },
        { name: "بستری", data: [22, 28, 25, 30, 24, 26, 10] },
      ],
    },
    secondary: {
      title: "بار بخش‌های بیمارستان",
      type: "bar",
      categories: ["اورژانس", "قلب", "ارتوپدی", "اعصاب", "زنان", "کودکان"],
      series: [
        { name: "بیمار بستری", data: [42, 35, 28, 22, 30, 18] },
        { name: "ظرفیت کل", data: [60, 45, 40, 30, 40, 25] },
      ],
    },
  },
  tableData: [
    {
      id: "hc-t1",
      patientName: "علی محمدی",
      doctor: "دکتر رضایی",
      department: "قلب",
      date: "۱۴۰۳/۰۲/۱۵",
      status: "بستری",
      fee: "۴۵۰,۰۰۰ ت",
    },
    {
      id: "hc-t2",
      patientName: "زهرا کریمی",
      doctor: "دکتر حسینی",
      department: "زنان",
      date: "۱۴۰۳/۰۲/۱۵",
      status: "سرپایی",
      fee: "۱۸۰,۰۰۰ ت",
    },
    {
      id: "hc-t3",
      patientName: "محمد احمدی",
      doctor: "دکتر جعفری",
      department: "اورژانس",
      date: "۱۴۰۳/۰۲/۱۴",
      status: "ترخیص شد",
      fee: "۶۸۰,۰۰۰ ت",
    },
    {
      id: "hc-t4",
      patientName: "لیلا نظری",
      doctor: "دکتر عباسی",
      department: "اعصاب",
      date: "۱۴۰۳/۰۲/۱۴",
      status: "بستری",
      fee: "۳۲۰,۰۰۰ ت",
    },
    {
      id: "hc-t5",
      patientName: "حسن رضوی",
      doctor: "دکتر موسوی",
      department: "ارتوپدی",
      date: "۱۴۰۳/۰۲/۱۳",
      status: "پیگیری",
      fee: "۲۴۰,۰۰۰ ت",
    },
    {
      id: "hc-t6",
      patientName: "فاطمه صادقی",
      doctor: "دکتر رضایی",
      department: "کودکان",
      date: "۱۴۰۳/۰۲/۱۳",
      status: "سرپایی",
      fee: "۱۵۰,۰۰۰ ت",
    },
  ],
  activityFeed: [
    {
      id: "b1",
      title: "بیمار جدید پذیرش شد",
      subtitle: "علی محمدی - اورژانس",
      time: "۵ دقیقه پیش",
      icon: "solar:user-plus-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "b2",
      title: "عمل جراحی انجام شد",
      subtitle: "دکتر جعفری - اتاق ۳",
      time: "۴۵ دقیقه پیش",
      icon: "solar:health-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "b3",
      title: "نوبت‌دهی آنلاین",
      subtitle: "۲۸ نوبت رزرو شد",
      time: "۲ ساعت پیش",
      icon: "solar:calendar-add-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "b4",
      title: "گزارش آزمایشگاه",
      subtitle: "نتایج بیمار #۱۲۴۵",
      time: "۳ ساعت پیش",
      icon: "solar:document-text-linear",
      iconBg: "bg-info/10",
      iconColor: "text-info",
    },
    {
      id: "b5",
      title: "بیمار ترخیص شد",
      subtitle: "محمد احمدی - بخش قلب",
      time: "دیروز",
      icon: "solar:exit-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
};

// ─── Insurance ───────────────────────────────────────────────────────────────
export const insuranceConfig: DomainConfig<InsuranceRow> = {
  type: "insurance",
  label: "بیمه",
  icon: "solar:shield-check-linear",
  stats: [
    {
      id: "ins1",
      label: "بیمه‌نامه فعال",
      value: "۲۴٬۵۱۲",
      change: "+۹٪",
      changeType: "up",
      icon: "solar:shield-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "ins2",
      label: "خسارت ثبت‌شده",
      value: "۱٬۲۳۴",
      change: "+۲۲٪",
      changeType: "down",
      icon: "solar:danger-triangle-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
    {
      id: "ins3",
      label: "نرخ تائید خسارت",
      value: "۷۴٪",
      change: "+۳٪",
      changeType: "up",
      icon: "solar:check-circle-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "ins4",
      label: "درآمد حق بیمه",
      value: "۸۵ میلیارد",
      change: "+۱۱٪",
      changeType: "up",
      icon: "solar:money-bag-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
  ],
  charts: {
    primary: {
      title: "روند خسارت‌ها (ماهانه)",
      type: "line",
      categories: [
        "فروردین",
        "اردیبهشت",
        "خرداد",
        "تیر",
        "مرداد",
        "شهریور",
        "مهر",
        "آبان",
        "آذر",
        "دی",
        "بهمن",
        "اسفند",
      ],
      series: [
        {
          name: "ثبت‌شده",
          data: [85, 92, 78, 105, 98, 112, 88, 124, 115, 130, 142, 108],
        },
        {
          name: "پرداخت‌شده",
          data: [70, 78, 65, 88, 82, 95, 74, 102, 96, 108, 118, 90],
        },
      ],
    },
    secondary: {
      title: "توزیع نوع بیمه‌نامه",
      type: "donut",
      categories: [],
      labels: ["عمر", "خودرو", "درمان", "آتش‌سوزی", "مسافرت"],
      series: [35, 28, 22, 10, 5],
    },
  },
  tableData: [
    {
      id: "ins-t1",
      claimId: "CLM-۱۰۴۵",
      policyHolder: "شرکت آریان",
      type: "آتش‌سوزی",
      amount: "۴۵۰ میلیون",
      date: "۱۴۰۳/۰۲/۱۵",
      status: "در بررسی",
    },
    {
      id: "ins-t2",
      claimId: "CLM-۱۰۴۴",
      policyHolder: "رضا مرادی",
      type: "خودرو",
      amount: "۱۸ میلیون",
      date: "۱۴۰۳/۰۲/۱۴",
      status: "تائید شد",
    },
    {
      id: "ins-t3",
      claimId: "CLM-۱۰۴۳",
      policyHolder: "مهناز کریمی",
      type: "درمان",
      amount: "۸.۵ میلیون",
      date: "۱۴۰۳/۰۲/۱۴",
      status: "پرداخت شد",
    },
    {
      id: "ins-t4",
      claimId: "CLM-۱۰۴۲",
      policyHolder: "نیکان سازه",
      type: "عمر",
      amount: "۱.۲ میلیارد",
      date: "۱۴۰۳/۰۲/۱۳",
      status: "رد شد",
    },
    {
      id: "ins-t5",
      claimId: "CLM-۱۰۴۱",
      policyHolder: "امیر حسینی",
      type: "مسافرت",
      amount: "۴.۸ میلیون",
      date: "۱۴۰۳/۰۲/۱۲",
      status: "تائید شد",
    },
    {
      id: "ins-t6",
      claimId: "CLM-۱۰۴۰",
      policyHolder: "گلناز رضایی",
      type: "درمان",
      amount: "۲۲ میلیون",
      date: "۱۴۰۳/۰۲/۱۲",
      status: "در بررسی",
    },
  ],
  activityFeed: [
    {
      id: "c1",
      title: "درخواست خسارت جدید",
      subtitle: "CLM-۱۰۴۵ - آتش‌سوزی",
      time: "۸ دقیقه پیش",
      icon: "solar:danger-triangle-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
    {
      id: "c2",
      title: "بیمه‌نامه صادر شد",
      subtitle: "بیمه عمر - امیر حسینی",
      time: "۱ ساعت پیش",
      icon: "solar:document-add-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "c3",
      title: "خسارت پرداخت شد",
      subtitle: "CLM-۱۰۴۳ - ۸.۵ میلیون",
      time: "۳ ساعت پیش",
      icon: "solar:check-circle-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "c4",
      title: "بررسی کارشناس",
      subtitle: "CLM-۱۰۴۲ - نیکان سازه",
      time: "دیروز",
      icon: "solar:eye-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "c5",
      title: "درخواست مدارک",
      subtitle: "CLM-۱۰۴۰ - گلناز رضایی",
      time: "دیروز",
      icon: "solar:paperclip-linear",
      iconBg: "bg-info/10",
      iconColor: "text-info",
    },
  ],
};

// ─── Digital Marketing ───────────────────────────────────────────────────────
export const marketingConfig: DomainConfig<MarketingRow> = {
  type: "marketing",
  label: "بازاریابی",
  icon: "solar:chart-2-linear",
  stats: [
    {
      id: "mkt1",
      label: "کل ترافیک",
      value: "۱.۴۸ میلیون",
      change: "+۲۳٪",
      changeType: "up",
      icon: "solar:graph-up-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "mkt2",
      label: "نرخ تبدیل",
      value: "۳.۶٪",
      change: "+۰.۴٪",
      changeType: "up",
      icon: "solar:target-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "mkt3",
      label: "هزینه هر کلیک",
      value: "۱٬۲۵۰ ت",
      change: "-۸٪",
      changeType: "up",
      icon: "solar:cursor-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "mkt4",
      label: "درآمد کمپین",
      value: "۴.۲ میلیارد",
      change: "+۱۷٪",
      changeType: "up",
      icon: "solar:wallet-money-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
  charts: {
    primary: {
      title: "منابع ترافیک",
      type: "donut",
      categories: [],
      labels: [
        "جستجوی ارگانیک",
        "شبکه اجتماعی",
        "ایمیل",
        "تبلیغات پولی",
        "مستقیم",
      ],
      series: [38, 25, 18, 12, 7],
    },
    secondary: {
      title: "عملکرد کمپین‌ها",
      type: "line",
      categories: [
        "هفته ۱",
        "هفته ۲",
        "هفته ۳",
        "هفته ۴",
        "هفته ۵",
        "هفته ۶",
        "هفته ۷",
        "هفته ۸",
      ],
      series: [
        {
          name: "کلیک",
          data: [4200, 5100, 4800, 6200, 5800, 7100, 6900, 8200],
        },
        { name: "تبدیل", data: [150, 188, 172, 224, 210, 256, 248, 296] },
      ],
    },
  },
  tableData: [
    {
      id: "mkt-t1",
      campaign: "کمپین عید نوروز",
      platform: "اینستاگرام",
      impressions: "۵۴۰,۰۰۰",
      clicks: "۱۸,۲۰۰",
      ctr: "۳.۳۷٪",
      cost: "۱۲۰ میلیون",
      roi: "۳۸۰٪",
    },
    {
      id: "mkt-t2",
      campaign: "تبلیغات گوگل",
      platform: "گوگل",
      impressions: "۱.۲ میلیون",
      clicks: "۴۵,۰۰۰",
      ctr: "۳.۷۵٪",
      cost: "۲۸۰ میلیون",
      roi: "۲۶۰٪",
    },
    {
      id: "mkt-t3",
      campaign: "ایمیل مارکتینگ",
      platform: "ایمیل",
      impressions: "۸۵,۰۰۰",
      clicks: "۱۲,۰۰۰",
      ctr: "۱۴.۱٪",
      cost: "۱۸ میلیون",
      roi: "۵۲۰٪",
    },
    {
      id: "mkt-t4",
      campaign: "کمپین تلگرام",
      platform: "تلگرام",
      impressions: "۳۲۰,۰۰۰",
      clicks: "۹,۸۰۰",
      ctr: "۳.۰۶٪",
      cost: "۴۵ میلیون",
      roi: "۱۸۰٪",
    },
    {
      id: "mkt-t5",
      campaign: "بنر سایت",
      platform: "وب",
      impressions: "۲.۸ میلیون",
      clicks: "۲۲,۴۰۰",
      ctr: "۰.۸٪",
      cost: "۶۵ میلیون",
      roi: "۱۴۰٪",
    },
    {
      id: "mkt-t6",
      campaign: "پوش نوتیفیکیشن",
      platform: "موبایل",
      impressions: "۱۵۰,۰۰۰",
      clicks: "۱۸,۰۰۰",
      ctr: "۱۲٪",
      cost: "۸ میلیون",
      roi: "۴۸۰٪",
    },
  ],
  activityFeed: [
    {
      id: "d1",
      title: "کمپین جدید راه‌اندازی شد",
      subtitle: "کمپین عید ۱۴۰۴",
      time: "۳۰ دقیقه پیش",
      icon: "solar:rocket-2-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "d2",
      title: "بودجه تبلیغات افزایش یافت",
      subtitle: "گوگل ادز +۵۰ میلیون",
      time: "۲ ساعت پیش",
      icon: "solar:graph-up-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "d3",
      title: "هدف تبدیل محقق شد",
      subtitle: "نرخ تبدیل ۳.۶٪",
      time: "۴ ساعت پیش",
      icon: "solar:target-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "d4",
      title: "گزارش هفتگی آماده شد",
      subtitle: "کمپین‌های هفته گذشته",
      time: "دیروز",
      icon: "solar:chart-linear",
      iconBg: "bg-info/10",
      iconColor: "text-info",
    },
    {
      id: "d5",
      title: "کمپین متوقف شد",
      subtitle: "بنر سایت - بودجه تمام",
      time: "دیروز",
      icon: "solar:pause-circle-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
};

// ─── Marketplace ─────────────────────────────────────────────────────────────
export const marketplaceConfig: DomainConfig<MarketplaceRow> = {
  type: "marketplace",
  label: "فروشگاه",
  icon: "solar:shop-2-linear",
  stats: [
    {
      id: "mp1",
      label: "کل سفارشات",
      value: "۱۸٬۴۵۶",
      change: "+۲۸٪",
      changeType: "up",
      icon: "solar:bag-5-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "mp2",
      label: "درآمد کل",
      value: "۲۴.۸ میلیارد",
      change: "+۳۵٪",
      changeType: "up",
      icon: "solar:wallet-money-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "mp3",
      label: "فروشنده فعال",
      value: "۳٬۲۱۴",
      change: "+۱۲٪",
      changeType: "up",
      icon: "solar:shop-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "mp4",
      label: "نرخ تبدیل",
      value: "۴.۲٪",
      change: "-۰.۳٪",
      changeType: "down",
      icon: "solar:target-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
  ],
  charts: {
    primary: {
      title: "فروش ماهانه",
      type: "area",
      categories: [
        "فروردین",
        "اردیبهشت",
        "خرداد",
        "تیر",
        "مرداد",
        "شهریور",
        "مهر",
        "آبان",
        "آذر",
        "دی",
        "بهمن",
        "اسفند",
      ],
      series: [
        {
          name: "درآمد (میلیون)",
          data: [
            1200, 1500, 1350, 1800, 2100, 1950, 2300, 2600, 2400, 2800, 3200,
            3800,
          ],
        },
        {
          name: "تعداد سفارش",
          data: [
            850, 1050, 980, 1250, 1450, 1380, 1600, 1820, 1700, 1950, 2200,
            2600,
          ],
        },
      ],
    },
    secondary: {
      title: "دسته‌بندی پرفروش",
      type: "bar",
      categories: ["الکترونیک", "پوشاک", "خانه", "ورزش", "کتاب", "آرایشی"],
      series: [{ name: "فروش", data: [4800, 3200, 2600, 1800, 1400, 2200] }],
    },
  },
  tableData: [
    {
      id: "mp-t1",
      orderId: "#ORD-۸۸۵۲",
      customer: "سینا موسوی",
      seller: "دیجی‌کالا",
      product: "گوشی Samsung S25",
      amount: "۳۲ میلیون",
      date: "۱۴۰۳/۰۲/۱۵",
      status: "ارسال شد",
    },
    {
      id: "mp-t2",
      orderId: "#ORD-۸۸۵۱",
      customer: "نرگس احمدی",
      seller: "آدیداس ایران",
      product: "کتانی ورزشی",
      amount: "۴.۵ میلیون",
      date: "۱۴۰۳/۰۲/۱۵",
      status: "در انتظار",
    },
    {
      id: "mp-t3",
      orderId: "#ORD-۸۸۵۰",
      customer: "کامران رضایی",
      seller: "بوک‌لند",
      product: "مجموعه کتاب",
      amount: "۸۸۰,۰۰۰ ت",
      date: "۱۴۰۳/۰۲/۱۴",
      status: "تحویل داده شد",
    },
    {
      id: "mp-t4",
      orderId: "#ORD-۸۸۴۹",
      customer: "مریم صادقی",
      seller: "آرایشگاه گلد",
      product: "پکیج مراقبت",
      amount: "۲.۲ میلیون",
      date: "۱۴۰۳/۰۲/۱۴",
      status: "ارسال شد",
    },
    {
      id: "mp-t5",
      orderId: "#ORD-۸۸۴۸",
      customer: "علی حیدری",
      seller: "تکنو شاپ",
      product: "لپ‌تاپ ایسوس",
      amount: "۴۸ میلیون",
      date: "۱۴۰۳/۰۲/۱۳",
      status: "مرجوع شد",
    },
    {
      id: "mp-t6",
      orderId: "#ORD-۸۸۴۷",
      customer: "پریسا کاظمی",
      seller: "فشن‌هاوس",
      product: "مانتو بهاره",
      amount: "۱.۸ میلیون",
      date: "۱۴۰۳/۰۲/۱۳",
      status: "تحویل داده شد",
    },
  ],
  activityFeed: [
    {
      id: "e1",
      title: "سفارش جدید ثبت شد",
      subtitle: "#ORD-۸۸۵۲ - ۳۲ میلیون",
      time: "۲ دقیقه پیش",
      icon: "solar:bag-5-linear",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
    },
    {
      id: "e2",
      title: "پرداخت تائید شد",
      subtitle: "کامران رضایی - کتاب",
      time: "۴۵ دقیقه پیش",
      icon: "solar:check-circle-linear",
      iconBg: "bg-success/10",
      iconColor: "text-success",
    },
    {
      id: "e3",
      title: "مرجوعی ثبت شد",
      subtitle: "#ORD-۸۸۴۸ - لپ‌تاپ",
      time: "۲ ساعت پیش",
      icon: "solar:arrow-left-linear",
      iconBg: "bg-error/10",
      iconColor: "text-error",
    },
    {
      id: "e4",
      title: "فروشنده جدید تائید شد",
      subtitle: "فشن‌هاوس",
      time: "۴ ساعت پیش",
      icon: "solar:shop-linear",
      iconBg: "bg-warning/10",
      iconColor: "text-warning",
    },
    {
      id: "e5",
      title: "نظر و ستاره ثبت شد",
      subtitle: "Samsung S25 - ۵ ستاره",
      time: "دیروز",
      icon: "solar:star-linear",
      iconBg: "bg-info/10",
      iconColor: "text-info",
    },
  ],
};

export const allDomainConfigs = {
  realEstate: realEstateConfig,
  healthcare: healthcareConfig,
  insurance: insuranceConfig,
  marketing: marketingConfig,
  marketplace: marketplaceConfig,
} as const;
