import { KanbanColumn } from "./types";
import { uniqueId } from "lodash";

export const initialColumns: KanbanColumn[] = [
  {
    id: uniqueId("col-"),
    title: "درخواست جدید",
    color: "#FF6B6B",
    cards: [
      {
        id: uniqueId("card-"),
        title: "آماده‌سازی محدوده پروژه",
        description: "تعریف اهداف، تیم و زمان‌بندی پروژه",
        priority: "عادی",
        assignees: ["/images/profile/user-1.jpg", "/images/profile/user-2.jpg"],
        image: "/images/blog/blog-img1.jpg",
        comments: 2,
        links: 1,
        tags: ["پروژه"],
      },
      {
        id: uniqueId("card-"),
        title: "جلسه اولیه با مشتری",
        description: "بررسی نیازمندی‌ها و انتظارات مشتری",
        priority: "متوسط",
        assignees: [
          "/images/profile/user-3.jpg",
          "/images/profile/user-4.jpg",
          "/images/profile/user-5.jpg",
        ],
        comments: 1,
        links: 0,
        tags: ["مشتری", "جلسه"],
      },
      {
        id: uniqueId("card-"),
        title: "جمع‌آوری نیازمندی‌های پروژه",
        description: "مستندسازی تمام نیازمندی‌های فنی و غیرفنی",
        priority: "عادی",
        assignees: ["/images/profile/user-6.jpg"],
        comments: 3,
        links: 2,
        tags: ["مستندات"],
      },
    ],
  },
  {
    id: uniqueId("col-"),
    title: "در حال انجام",
    color: "#4ECDC4",
    cards: [
      {
        id: uniqueId("card-"),
        title: "طراحی صفحه اصلی",
        description: "طراحی UI/UX صفحه اصلی وب‌سایت",
        priority: "بالا",
        assignees: ["/images/profile/user-1.jpg"],
        comments: 1,
        links: 0,
        tags: ["طراحی"],
      },
      {
        id: uniqueId("card-"),
        title: "راه‌اندازی محیط توسعه",
        description: "پیکربندی سرور، دیتابیس و ابزارهای توسعه",
        priority: "عادی",
        assignees: ["/images/profile/user-2.jpg", "/images/profile/user-4.jpg"],
        comments: 1,
        links: 0,
        tags: ["توسعه", "زیرساخت"],
      },
    ],
  },
  {
    id: uniqueId("col-"),
    title: "تکمیل شده",
    color: "#45B7D1",
    cards: [
      {
        id: uniqueId("card-"),
        title: "ایجاد وایرفریم",
        description: "طراحی اولیه ساختار صفحات",
        priority: "عادی",
        assignees: ["/images/profile/user-5.jpg"],
        comments: 1,
        links: 0,
        tags: ["طراحی"],
      },
      {
        id: uniqueId("card-"),
        title: "تأیید دستورالعمل برندینگ",
        description: "بررسی و تأیید رنگ‌ها، فونت‌ها و لوگو",
        priority: "عادی",
        assignees: ["/images/profile/user-3.jpg"],
        image: "/images/blog/blog-img2.jpg",
        comments: 1,
        links: 0,
        tags: ["برندینگ"],
      },
      {
        id: uniqueId("card-"),
        title: "نهایی کردن پرسوناهای کاربری",
        description: "تعریف پرسوناهای هدف بر اساس تحقیقات",
        priority: "بالا",
        assignees: ["/images/profile/user-6.jpg"],
        comments: 2,
        links: 1,
        tags: ["تحقیق"],
      },
      {
        id: uniqueId("card-"),
        title: "تحلیل رقبا",
        description: "بررسی محصولات مشابه در بازار",
        priority: "متوسط",
        assignees: ["/images/profile/user-1.jpg", "/images/profile/user-2.jpg"],
        comments: 0,
        links: 3,
        tags: ["تحلیل", "بازار"],
      },
    ],
  },
  {
    id: uniqueId("col-"),
    title: "باقی‌مانده",
    color: "#96CEB4",
    cards: [
      {
        id: uniqueId("card-"),
        title: "برنامه‌ریزی لانچ بازاریابی",
        description: "تدوین استراتژی معرفی محصول به بازار",
        priority: "عادی",
        assignees: ["/images/profile/user-4.jpg"],
        comments: 1,
        links: 0,
        tags: ["بازاریابی"],
      },
    ],
  },
];
